### ISSUE TITLE
在load提前训练的lbf模型时出现错误

### ISSUE THREAD

**Issue by ckzbullbullet** [amusi/opencv-facial-landmark-detection#1]
从提供的链接下载了lbfmodel.yaml 模型，但是在载入并应用的过程中，出现错误：
OpenCV(3.4.1) Error: Parsing error (C:/cv341/data/face-alignment/model/lbfmodel.yaml(805185): Unexpected end of line) in icvYMLGetMultilineStringContent, file c:\opencv_with_extra\sources\opencv\modules\core\src\persistence_yml.cpp, line 79

看起来是模型yaml的格式错误。 请问怎么处理？

**Comment by wuwuhuz** [comment]
同问。。博主
